[[Glibmm]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a6ff605494d70eae7049f7f512cd1d1783f7af46"
os = "macos"

    [[Glibmm.download]]
    sha256 = "8050aa890a93710f603f9203e6bcaa31662316cca810f2525d2e00b4d9a17668"
    url = "https://github.com/JuliaBinaryWrappers/Glibmm_jll.jl/releases/download/Glibmm-v2.76.0+0/Glibmm.v2.76.0.aarch64-apple-darwin-cxx03.tar.gz"
[[Glibmm]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d7a60d687377d2f19f92f8ed76bdf249c750e2e7"
os = "macos"

    [[Glibmm.download]]
    sha256 = "bd2893fe97a8fed69234fdfe0dbc3534fdcabe7d09eb47506a8cc3a0c31b2b27"
    url = "https://github.com/JuliaBinaryWrappers/Glibmm_jll.jl/releases/download/Glibmm-v2.76.0+0/Glibmm.v2.76.0.aarch64-apple-darwin-cxx11.tar.gz"
[[Glibmm]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a75ac8e98a01f1efd78c6015a61449f42d91e950"
libc = "glibc"
os = "linux"

    [[Glibmm.download]]
    sha256 = "f54f25924bf8903ba159b288de0f9a3e1fde7be02a8697dcebcb564547f4fae8"
    url = "https://github.com/JuliaBinaryWrappers/Glibmm_jll.jl/releases/download/Glibmm-v2.76.0+0/Glibmm.v2.76.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Glibmm]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "44cff689b71013fdb452ef05707dfa09a7a96ed5"
libc = "glibc"
os = "linux"

    [[Glibmm.download]]
    sha256 = "d6e2c7945d34907ead8fc5eda1c0e93206efe901e174dcf4ef37f6791ef8d44d"
    url = "https://github.com/JuliaBinaryWrappers/Glibmm_jll.jl/releases/download/Glibmm-v2.76.0+0/Glibmm.v2.76.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Glibmm]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "113a7bef4266a27cf427f05e12e15ebb217c69fb"
libc = "musl"
os = "linux"

    [[Glibmm.download]]
    sha256 = "f31032d835de618b8e04d6791f06394eeb891fc70eaa666bc48cb9bdbff3a0b2"
    url = "https://github.com/JuliaBinaryWrappers/Glibmm_jll.jl/releases/download/Glibmm-v2.76.0+0/Glibmm.v2.76.0.aarch64-linux-musl-cxx03.tar.gz"
[[Glibmm]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4d14c0897ef590a1f1b85b55abe5a4809b5c3143"
libc = "musl"
os = "linux"

    [[Glibmm.download]]
    sha256 = "b749e37255b47c812c028876d7b3dad3def360ebcc338141d66c045693796602"
    url = "https://github.com/JuliaBinaryWrappers/Glibmm_jll.jl/releases/download/Glibmm-v2.76.0+0/Glibmm.v2.76.0.aarch64-linux-musl-cxx11.tar.gz"
[[Glibmm]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8b37b30504b84550fe1c150ff3fbffc210dc783c"
libc = "glibc"
os = "linux"

    [[Glibmm.download]]
    sha256 = "d60f91e4a15e6cf8df27b646f675db809ab22f0dd54f32947938d8af5355d52a"
    url = "https://github.com/JuliaBinaryWrappers/Glibmm_jll.jl/releases/download/Glibmm-v2.76.0+0/Glibmm.v2.76.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Glibmm]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5c8401a6be37770f7e506ce6dd9227b4c24c0bcf"
libc = "glibc"
os = "linux"

    [[Glibmm.download]]
    sha256 = "5f44cb8303cab9d423a43c4b843b9e45933fa0169c8c2cfbf48f323c7ea2320c"
    url = "https://github.com/JuliaBinaryWrappers/Glibmm_jll.jl/releases/download/Glibmm-v2.76.0+0/Glibmm.v2.76.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Glibmm]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "285c96946834eb04d30ea930606c27fe39531bea"
libc = "musl"
os = "linux"

    [[Glibmm.download]]
    sha256 = "edf5de08f7368065774e256801e3c7c5b05838c0a8f57dcfc0a349a7773696ed"
    url = "https://github.com/JuliaBinaryWrappers/Glibmm_jll.jl/releases/download/Glibmm-v2.76.0+0/Glibmm.v2.76.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Glibmm]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b62a9a2b95adf2f7ad8d625f56a2fb6ebd38c85d"
libc = "musl"
os = "linux"

    [[Glibmm.download]]
    sha256 = "754774355e752226c4120c432eff97199efe4ee3eab78e16a02079cc63daaf99"
    url = "https://github.com/JuliaBinaryWrappers/Glibmm_jll.jl/releases/download/Glibmm-v2.76.0+0/Glibmm.v2.76.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Glibmm]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "39642377dfea835bb9ad0f589b73576e55ca857d"
libc = "glibc"
os = "linux"

    [[Glibmm.download]]
    sha256 = "74c006dd833f3c5e8242e222916627800c83d230ffc5b8725bbab2dbebdd74fc"
    url = "https://github.com/JuliaBinaryWrappers/Glibmm_jll.jl/releases/download/Glibmm-v2.76.0+0/Glibmm.v2.76.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Glibmm]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "93bcb2a258f215eca0c9f7b29605e18dd2008f28"
libc = "glibc"
os = "linux"

    [[Glibmm.download]]
    sha256 = "21404a7cf11c7962cb49de7445ec52d3e077d70666c92e9cbe9c0124d863c562"
    url = "https://github.com/JuliaBinaryWrappers/Glibmm_jll.jl/releases/download/Glibmm-v2.76.0+0/Glibmm.v2.76.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Glibmm]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "871cb9eb8fb88c99112253a83982356aca50b09b"
libc = "musl"
os = "linux"

    [[Glibmm.download]]
    sha256 = "197afc625682ec6e78ddce28a5c4185782f22697f9b927d66db57e8951c19843"
    url = "https://github.com/JuliaBinaryWrappers/Glibmm_jll.jl/releases/download/Glibmm-v2.76.0+0/Glibmm.v2.76.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Glibmm]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "88f81ffa267c33e783a40d1876bab765378b5d71"
libc = "musl"
os = "linux"

    [[Glibmm.download]]
    sha256 = "2b2fe5ee0ec3f7f2820788a5cd3f9bcdb0cc6d27ee8239079949a393d1b82e8a"
    url = "https://github.com/JuliaBinaryWrappers/Glibmm_jll.jl/releases/download/Glibmm-v2.76.0+0/Glibmm.v2.76.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Glibmm]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0a3d7698da5e001c88bfa58e9c72693df25ee383"
libc = "glibc"
os = "linux"

    [[Glibmm.download]]
    sha256 = "7cacf58b03219f0450f9291205dabd860c873ac510533fff7c91a044bfcf77aa"
    url = "https://github.com/JuliaBinaryWrappers/Glibmm_jll.jl/releases/download/Glibmm-v2.76.0+0/Glibmm.v2.76.0.i686-linux-gnu-cxx03.tar.gz"
[[Glibmm]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b98c676ab0cf3ef09b41efaa90b4b2cb61f09f55"
libc = "glibc"
os = "linux"

    [[Glibmm.download]]
    sha256 = "dfa09d56b7d6c772bd56f2fbf67169e45f6e8466a041df82f9e348f39ddf73b6"
    url = "https://github.com/JuliaBinaryWrappers/Glibmm_jll.jl/releases/download/Glibmm-v2.76.0+0/Glibmm.v2.76.0.i686-linux-gnu-cxx11.tar.gz"
[[Glibmm]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e147daa9b7baf0446c03f9ae13a5a2d5c0c8538b"
libc = "musl"
os = "linux"

    [[Glibmm.download]]
    sha256 = "58885e2b7ffbc207239c487687e94c8fba62c0cbfad1d17a87a14d03b1ed36fa"
    url = "https://github.com/JuliaBinaryWrappers/Glibmm_jll.jl/releases/download/Glibmm-v2.76.0+0/Glibmm.v2.76.0.i686-linux-musl-cxx03.tar.gz"
[[Glibmm]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "40e0f1e3d028a81351b2ff9df0a4e36ea05a6cf4"
libc = "musl"
os = "linux"

    [[Glibmm.download]]
    sha256 = "86aadf1d005cbf9e1319da3113d2d6ef528bd71b2670f6a04b71c2bdf41c56ff"
    url = "https://github.com/JuliaBinaryWrappers/Glibmm_jll.jl/releases/download/Glibmm-v2.76.0+0/Glibmm.v2.76.0.i686-linux-musl-cxx11.tar.gz"
[[Glibmm]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5f579d22ec593b94e11736757f0624959c4d9cbf"
os = "windows"

    [[Glibmm.download]]
    sha256 = "ee5e12dcb4fe6347861098a02b53eec9ed1aa9621230e5c5edbc08043169cc21"
    url = "https://github.com/JuliaBinaryWrappers/Glibmm_jll.jl/releases/download/Glibmm-v2.76.0+0/Glibmm.v2.76.0.i686-w64-mingw32-cxx03.tar.gz"
[[Glibmm]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "03bde90b867772d815a4e6bd12fcaca6f4368f34"
os = "windows"

    [[Glibmm.download]]
    sha256 = "8ab8b354ce17ac43516da5d6a506da72c24ebca1e2607a104efed0282ee9f446"
    url = "https://github.com/JuliaBinaryWrappers/Glibmm_jll.jl/releases/download/Glibmm-v2.76.0+0/Glibmm.v2.76.0.i686-w64-mingw32-cxx11.tar.gz"
[[Glibmm]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cbd5e2933d5a09b0e75aa6cbda66fdf8631e9987"
libc = "glibc"
os = "linux"

    [[Glibmm.download]]
    sha256 = "eaa517ac10d029d155fc14a2e55a1fb061e317a706902fd8a7c4af9589ecc921"
    url = "https://github.com/JuliaBinaryWrappers/Glibmm_jll.jl/releases/download/Glibmm-v2.76.0+0/Glibmm.v2.76.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Glibmm]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "13224e60a8aa37244b756b004e550f559797f867"
libc = "glibc"
os = "linux"

    [[Glibmm.download]]
    sha256 = "1b71f8befe79e9865b083bbbcf973ec83ae500a6d4e32cf69a6afa5450e8cef1"
    url = "https://github.com/JuliaBinaryWrappers/Glibmm_jll.jl/releases/download/Glibmm-v2.76.0+0/Glibmm.v2.76.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Glibmm]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "26dbfbe0522f2e76d64fb0d3fcfbb53279ebfd54"
os = "macos"

    [[Glibmm.download]]
    sha256 = "81feb6c49821e5bba6a0f862ab02f326848074db932f73d2acbd1707a74c4f61"
    url = "https://github.com/JuliaBinaryWrappers/Glibmm_jll.jl/releases/download/Glibmm-v2.76.0+0/Glibmm.v2.76.0.x86_64-apple-darwin-cxx03.tar.gz"
[[Glibmm]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "64306ad881f86c5f05cc34b8f8377184c01baf71"
os = "macos"

    [[Glibmm.download]]
    sha256 = "8eea0d6b43cdd46d238a35022520d8460c68a92e92c3289485d8136234b8011b"
    url = "https://github.com/JuliaBinaryWrappers/Glibmm_jll.jl/releases/download/Glibmm-v2.76.0+0/Glibmm.v2.76.0.x86_64-apple-darwin-cxx11.tar.gz"
[[Glibmm]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "097eadb9f8db17450422edb74e023cbc178311a4"
libc = "glibc"
os = "linux"

    [[Glibmm.download]]
    sha256 = "32d957fc1f8e947a43e3a1d151cc347392222251cb50a1c0de021605f2e6b94a"
    url = "https://github.com/JuliaBinaryWrappers/Glibmm_jll.jl/releases/download/Glibmm-v2.76.0+0/Glibmm.v2.76.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Glibmm]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8c346daa54cd80c6fc4c61e732046568cbcd1784"
libc = "glibc"
os = "linux"

    [[Glibmm.download]]
    sha256 = "0945868aa56392d883149db0c8b87a9c33d6aed46862f0ee2450998e7eb371fb"
    url = "https://github.com/JuliaBinaryWrappers/Glibmm_jll.jl/releases/download/Glibmm-v2.76.0+0/Glibmm.v2.76.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Glibmm]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "afeb94ffcd62988d432c07b0c76a7622961f200e"
libc = "musl"
os = "linux"

    [[Glibmm.download]]
    sha256 = "d437ce3ca43ee7ae04e9ea1396ae4f82eec490b1e7065dc6e606693f8141d4e5"
    url = "https://github.com/JuliaBinaryWrappers/Glibmm_jll.jl/releases/download/Glibmm-v2.76.0+0/Glibmm.v2.76.0.x86_64-linux-musl-cxx03.tar.gz"
[[Glibmm]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "40315458128c5384e2e451a9f70a128dc981a07a"
libc = "musl"
os = "linux"

    [[Glibmm.download]]
    sha256 = "5408ea294fc35b34ad0227161e66961eaecd9b5d9f3627082281fac9849a27de"
    url = "https://github.com/JuliaBinaryWrappers/Glibmm_jll.jl/releases/download/Glibmm-v2.76.0+0/Glibmm.v2.76.0.x86_64-linux-musl-cxx11.tar.gz"
[[Glibmm]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "adcdbc1297556be9bdc81f70959f8f18c64f7ef5"
os = "freebsd"

    [[Glibmm.download]]
    sha256 = "2472d9f7da57f64c4a4be7fffde2037b761522e2b0e1bfb00068615816b419a6"
    url = "https://github.com/JuliaBinaryWrappers/Glibmm_jll.jl/releases/download/Glibmm-v2.76.0+0/Glibmm.v2.76.0.x86_64-unknown-freebsd-cxx03.tar.gz"
[[Glibmm]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "00c1b24467fd2f048f1b926bdda818a2cb9204f7"
os = "freebsd"

    [[Glibmm.download]]
    sha256 = "7b3fcb0b82a93821678d66d9bd71e52398e22fc2c82ae4db3c87f5d5033c7d9e"
    url = "https://github.com/JuliaBinaryWrappers/Glibmm_jll.jl/releases/download/Glibmm-v2.76.0+0/Glibmm.v2.76.0.x86_64-unknown-freebsd-cxx11.tar.gz"
[[Glibmm]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "292faa64f5382531b90fa5e4622667a6bd7b3065"
os = "windows"

    [[Glibmm.download]]
    sha256 = "42dd94bf6be429fcab67a1275ff3785b6a02ec1857b9a3f497f1b6aac46dde35"
    url = "https://github.com/JuliaBinaryWrappers/Glibmm_jll.jl/releases/download/Glibmm-v2.76.0+0/Glibmm.v2.76.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Glibmm]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a828032c91017cf737f3207f90c3cddb419f5288"
os = "windows"

    [[Glibmm.download]]
    sha256 = "521e99744faf393ad41de4bf98452febb985bb2cbc9050ff1c76bb6f8a1170d1"
    url = "https://github.com/JuliaBinaryWrappers/Glibmm_jll.jl/releases/download/Glibmm-v2.76.0+0/Glibmm.v2.76.0.x86_64-w64-mingw32-cxx11.tar.gz"
